#!/usr/bin/env tsx

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'fs'
import { resolve } from 'path'
import {
  svgToJsx,
  extractSvgInner,
  extractViewBox,
  createComponentName,
  capitalize,
  parameterizeIds,
} from './svg-to-jsx'
import {
  loadCatalogue,
  toIdentityAssets,
  type Catalogue,
} from './lib/catalogue'
import type {
  TokenAsset,
  ChainAsset,
  BrandAsset,
  FrameAsset,
} from './lib/catalogue'
import { dominantColor } from './lib/dominant-color'
import { bold, cyan, dim, green, padLabel, yellow } from './lib/ansi'
import { buildIdentityIndexes } from '../packages/core/src/internal/identity'
import type { AliasCollision } from '../packages/core/src/internal/identity'
import { encodeMetaTable, encodeAliasTable } from './lib/codec'
import type { MetaRowInput } from './lib/codec'

const ROOT = resolve(process.cwd())
const CORE_GEN = resolve(ROOT, 'packages/core/src/generated')
const REACT_GEN = resolve(ROOT, 'packages/react/src/generated')

// --- In-memory output accumulation ---
//
// Every generated file is built into this map first. Nothing is written
// until the whole run is known-good: a fatal alias collision aborts BEFORE
// any write, so a failed generate can never leave poisoned src/generated/
// that a later build compiles.
const outputs = new Map<string, string>()

function emit(path: string, content: string) {
  outputs.set(path, content)
}

// --- Utilities ---

function escapeForTemplate(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')
}

function toSafeVarName(s: string): string {
  let result = s.replace(/[-_](\w)/g, (_, c) => c.toUpperCase())
  result = result.replace(/[^a-zA-Z0-9_$]/g, '')
  if (/^\d/.test(result)) {
    result = '_' + result
  }
  if (!/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(result)) {
    throw new Error(
      `Cannot create safe JS variable name from "${s}" (got "${result}")`,
    )
  }
  return result
}

// --- Generate Core Package ---

function generateCoreMeta(
  tokens: TokenAsset[],
  chains: ChainAsset[],
  brands: BrandAsset[],
) {
  // placeholderColor is the dominant colour of the full SVG; absent means the
  // glyph had no single dominant colour. The encoder collapses it to empty
  // when it equals brandColor, so equal-colour icons cost one field, not two.
  const pc = (svg: string): string | undefined =>
    dominantColor(svg) ?? undefined

  const tokenRows: MetaRowInput[] = tokens.map((t) => ({
    id: t.id,
    name: t.name,
    brandColor: t.brandColor,
    placeholderColor: pc(t.fullSvg),
    symbol: t.symbol,
  }))
  const chainRows: MetaRowInput[] = chains.map((c) => ({
    id: c.id,
    name: c.name,
    brandColor: c.brandColor,
    placeholderColor: pc(c.fullSvg),
    chainId: c.chainId,
  }))
  const brandRows: MetaRowInput[] = brands.map((b) => ({
    id: b.id,
    name: b.name,
    brandColor: b.brandColor,
    placeholderColor: pc(b.fullSvg),
  }))

  // Each per-type table is one control-char-framed string; the decoder rebuilds
  // the same Record<IdentityKey, IconMeta> at module init. JSON.stringify emits
  // the framing control chars as \uXXXX escapes inside a plain double-quoted
  // JS string literal — safe, with no template-literal escaping hazards.
  return [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    '',
    "import type { IconMeta, IconType } from '../types'",
    "import type { IdentityKey } from '../internal/identity'",
    "import { decodeMeta } from '../internal/codec'",
    '',
    `const ENCODED: Record<IconType, string> = {`,
    `  token: ${JSON.stringify(encodeMetaTable(tokenRows))},`,
    `  chain: ${JSON.stringify(encodeMetaTable(chainRows))},`,
    `  brand: ${JSON.stringify(encodeMetaTable(brandRows))},`,
    `}`,
    '',
    'export const META: Record<IdentityKey, IconMeta> = decodeMeta(ENCODED)',
    '',
  ].join('\n')
}

// String-literal unions of every shipped canonical id. Exported for
// consumers that want compile-time exhaustiveness (icon pickers, config
// maps) — the resolver functions intentionally keep accepting arbitrary
// strings, since aliases/symbols/chain ids are part of the input surface.
// Named *IconId (not ChainId) because IconMeta.chainId is the NUMERIC
// chain id — a string union called ChainId would be a footgun.
function generateCoreIds(
  tokens: TokenAsset[],
  chains: ChainAsset[],
  brands: BrandAsset[],
) {
  const union = (assets: { id: string }[]): string =>
    assets.length === 0
      ? ' never'
      : '\n' + assets.map((a) => `  | ${JSON.stringify(a.id)}`).join('\n')

  return [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    '',
    `export type TokenIconId =${union(tokens)}`,
    '',
    `export type ChainIconId =${union(chains)}`,
    '',
    `export type BrandIconId =${union(brands)}`,
    '',
    'export type IconId = TokenIconId | ChainIconId | BrandIconId',
    '',
  ].join('\n')
}

function generateCoreAliases(cat: Catalogue) {
  const identityIndexes = buildIdentityIndexes(toIdentityAssets(cat))
  aliasWarnings.push(...identityIndexes.warnings)
  sameTypeCollisions.push(
    ...identityIndexes.collisions.filter((c) => c.kept.type === c.dropped.type),
  )

  // Only the per-type maps are encoded; the cross-type map is derived at
  // module init (internal/identity.ts buildGlobalAliases) so every alias ships
  // exactly once. Each row drops the id's own normalized self-key (the decoder
  // re-adds it) and carries whatever extra keys buildIdentityIndexes produced
  // (symbol/chainId-derived + authored aliases) verbatim — the decode never
  // re-derives, keeping generate-time the single source of truth.
  return [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    '',
    "import type { IconType } from '../types'",
    "import { decodeAliases } from '../internal/codec'",
    '',
    `const ENCODED: Record<IconType, string> = {`,
    `  token: ${JSON.stringify(encodeAliasTable(identityIndexes.typeAliases.token))},`,
    `  chain: ${JSON.stringify(encodeAliasTable(identityIndexes.typeAliases.chain))},`,
    `  brand: ${JSON.stringify(encodeAliasTable(identityIndexes.typeAliases.brand))},`,
    `}`,
    '',
    'export const TYPE_ALIASES: Record<IconType, Record<string, string>> =',
    '  decodeAliases(ENCODED)',
    '',
  ].join('\n')
}

function generateCoreSvgExports(
  assets: (TokenAsset | ChainAsset | BrandAsset)[],
  category: string,
) {
  const lines: string[] = [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    '',
    "import type { IconVariant } from '../../types'",
    '',
  ]

  for (const a of assets) {
    const camel = toSafeVarName(a.id)
    lines.push(
      `export const ${camel}Full = \`${escapeForTemplate(a.fullSvg.trim())}\``,
    )
    lines.push(
      `export const ${camel}Mono = \`${escapeForTemplate(a.monoSvg.trim())}\``,
    )
    lines.push('')
  }

  // Lookup map for function access. NOTE: the map pins every icon of the
  // type — importing the getter retains the whole shard. Per-icon named
  // consts above stay tree-shakeable.
  lines.push(
    `const SVG_MAP: Record<string, { full: string; mono: string }> = {`,
  )
  for (const a of assets) {
    const camel = toSafeVarName(a.id)
    lines.push(
      `  ${JSON.stringify(a.id)}: { full: ${camel}Full, mono: ${camel}Mono },`,
    )
  }
  lines.push('}')
  lines.push('')
  lines.push(
    `export function get${capitalize(category)}Svg(id: string, variant: IconVariant = 'full'): string | null {`,
  )
  lines.push(`  const entry = SVG_MAP[id]`)
  lines.push(`  return entry ? entry[variant] : null`)
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

// --- Generate React Package ---

type Variant = 'full' | 'mono'

interface ComponentSpec {
  // The SVG markup for each variant.
  fullSvg: string
  monoSvg: string
  // Component identity + aria.
  componentName: string
  ariaLabel: string
  // The props type imported per emitted file.
  propsType: 'IconProps' | 'FrameIconProps'
}

// displayName MUST be gated behind NODE_ENV: the barrel entry and shared
// eager chunks are single modules after bundling, and an unconditional
// `X.displayName = ...` is a top-level side effect that forces a consumer's
// bundler to keep EVERY component in any module it touches — importing one
// icon from the barrel would drag all of its chunk-mates along. With the
// gate, production builds replace NODE_ENV, the branch goes dead, and the
// unreferenced components tree-shake away (fixtures/consumer/tree-shake.mjs
// guards this). The `typeof process` check mirrors src/env.d.ts: no-bundler
// ESM consumers (CDN) have no `process` and must not throw.
function displayNameLines(componentName: string): string[] {
  return [
    "if (typeof process !== 'undefined' && process.env.NODE_ENV !== 'production') {",
    `  ${componentName}.displayName = '${componentName}'`,
    '}',
  ]
}

// One variant SVG file: a forwardRef component whose default export contains
// ONLY this variant's markup, so a mono-only consumer's lazy chunk never
// downloads the full art (or vice versa). `mono` is destructured-and-
// discarded so it never lands on the DOM element. Mirrors the per-variant
// branch the combined component used to inline.
function generateVariantFile(spec: ComponentSpec, variant: Variant): string {
  const svg = variant === 'mono' ? spec.monoSvg : spec.fullSvg
  // SVG resource ids (clipPaths, gradients) must be unique per mounted
  // INSTANCE, not just per asset: url(#...) resolves document-wide to the
  // first match, so a second copy of the same icon — e.g. one in a hidden
  // drawer — hijacks the refs of every visible copy and blanks it. Icons
  // that define ids get a useId()-derived prefix baked into ids and refs.
  const { jsx: inner, idCount } = parameterizeIds(
    extractSvgInner(svgToJsx(svg)),
  )
  const viewBox = extractViewBox(svg) || '0 0 32 32'
  // Suffixed so React DevTools distinguishes the variant actually mounted
  // (the combined component renders one of the two).
  const variantName = `${spec.componentName}${capitalize(variant)}`

  let fillAttr: string
  if (variant === 'mono') {
    // Mono root fill: stroke-only art (outline glyphs / frame rings) must
    // keep fill="none" so shapes aren't filled solid; filled glyphs inherit
    // currentColor. A mono SVG that fills explicitly opts back in.
    const strokeOnly =
      /stroke="currentColor"/.test(svg) && !/fill="currentColor"/.test(svg)
    fillAttr = strokeOnly ? ' fill="none"' : ' fill="currentColor"'
  } else {
    // Preserve an explicit fill="none" on the full SVG root if present.
    fillAttr = /<svg[^>]*fill="none"/.test(svg) ? ' fill="none"' : ''
  }

  // `mono` is consumed by the combined component; here it is discarded so
  // it never reaches the DOM <svg>. Icons that define resource ids get a
  // per-instance prefix: useId() is unique per mount and SSR-stable, and the
  // sanitize strips React's delimiter characters (`:` / `«»`), which are not
  // safe inside an unquoted CSS url() token.
  const bodyLines =
    idCount > 0
      ? [
          '  ({ mono: _mono, size = 32, ...props }, ref) => {',
          "    const uid = useId().replace(/[^a-zA-Z0-9_-]/g, '')",
          '    return (',
          `      <svg ref={ref} width={size} height={size} viewBox="${viewBox}"${fillAttr} role="img" aria-label="${spec.ariaLabel}" {...props}>`,
          `        ${inner}`,
          '      </svg>',
          '    )',
          '  },',
        ]
      : [
          '  ({ mono: _mono, size = 32, ...props }, ref) => (',
          `    <svg ref={ref} width={size} height={size} viewBox="${viewBox}"${fillAttr} role="img" aria-label="${spec.ariaLabel}" {...props}>`,
          `      ${inner}`,
          '    </svg>',
          '  ),',
        ]

  return [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    idCount > 0
      ? "import { forwardRef, useId } from 'react'"
      : "import { forwardRef } from 'react'",
    `import type { ${spec.propsType} } from '../../icon-props'`,
    '',
    // PURE annotation: forwardRef() is opaque to bundlers, and chunk-mates
    // inside one shared module are only droppable when the init is provably
    // side-effect-free. Together with the NODE_ENV displayName gate this is
    // what makes single-icon imports tree-shake (see tree-shake.mjs fixture).
    `const ${variantName} = /* @__PURE__ */ forwardRef<SVGSVGElement, ${spec.propsType}>(`,
    ...bodyLines,
    ')',
    ...displayNameLines(variantName),
    '',
    `export default ${variantName}`,
    '',
  ].join('\n')
}

// The combined named component: a thin forwardRef that statically imports
// both variant components and renders one based on `mono`. No SVG markup is
// duplicated here — it lives in the two variant files.
function generateCombinedComponent(
  spec: ComponentSpec,
  fileBase: string,
): string {
  return [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    "import { forwardRef } from 'react'",
    `import type { ${spec.propsType} } from '../../icon-props'`,
    `import ${spec.componentName}Full from './${fileBase}.full'`,
    `import ${spec.componentName}Mono from './${fileBase}.mono'`,
    '',
    `export const ${spec.componentName} = /* @__PURE__ */ forwardRef<SVGSVGElement, ${spec.propsType}>(`,
    '  ({ mono = false, ...props }, ref) =>',
    `    mono ? (`,
    `      <${spec.componentName}Mono ref={ref} {...props} />`,
    `    ) : (`,
    `      <${spec.componentName}Full ref={ref} {...props} />`,
    `    ),`,
    ')',
    ...displayNameLines(spec.componentName),
    '',
  ].join('\n')
}

function assetSpec(asset: TokenAsset | ChainAsset | BrandAsset): ComponentSpec {
  return {
    fullSvg: asset.fullSvg,
    monoSvg: asset.monoSvg,
    componentName: createComponentName(asset.id),
    ariaLabel: asset.name.replace(/"/g, '&quot;'),
    propsType: 'IconProps',
  }
}

function frameSpec(frame: FrameAsset): ComponentSpec {
  return {
    fullSvg: frame.fullSvg,
    monoSvg: frame.monoSvg,
    componentName: createComponentName(frame.id, 'Frame'),
    ariaLabel:
      frame.id.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()) +
      ' Frame',
    propsType: 'FrameIconProps',
  }
}

// Emits the two variant files + the combined component for one asset/frame.
function emitComponentTrio(dir: string, fileBase: string, spec: ComponentSpec) {
  emit(resolve(dir, `${fileBase}.full.tsx`), generateVariantFile(spec, 'full'))
  emit(resolve(dir, `${fileBase}.mono.tsx`), generateVariantFile(spec, 'mono'))
  emit(
    resolve(dir, `${fileBase}.tsx`),
    generateCombinedComponent(spec, fileBase),
  )
}

function generateReactBarrelIndex(
  assets: (TokenAsset | ChainAsset | BrandAsset)[],
): string {
  const lines: string[] = [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    '',
  ]

  for (const a of assets) {
    const componentName = createComponentName(a.id)
    lines.push(`export { ${componentName} } from './${a.id}'`)
  }
  lines.push('')
  lines.push(`export type { IconProps } from '../../icon-props'`)
  lines.push('')

  return lines.join('\n')
}

// A lazy icon resolves through THREE steps now: per-type dispatcher -> shard
// file (keyed by the id's first char) -> per-variant icon chunk. The dispatcher
// is small (one thunk per distinct first char) and stays the dynamic-import
// entry point; the heavy id -> { full, mono } maps live in the shard files, so
// the first lazy render only downloads the one shard the id falls into instead
// of the whole type's map.
//
// Fan-out: a type with <= SHARD_FANOUT_THRESHOLD lazy ids emits ONE shard file
// ('_all') and every present first-char key points at it (multiple keys -> one
// file is fine and keeps lazy-icons.ts trivial). Above the threshold, one shard
// file per first character. Every import specifier is a static string literal
// (no template paths) so the bundler can code-split.
const SHARD_FANOUT_THRESHOLD = 64
const SINGLE_SHARD_KEY = '_all'

function shardKey(id: string): string {
  return id[0]
}

// Returns the dispatcher module plus the shard files for one type. The lazy
// assets are partitioned by first char; below threshold they all collapse into
// one '_all' file pointed at by every present first-char key.
function generateLazyType(
  assets: (TokenAsset | ChainAsset | BrandAsset)[],
  dirName: 'tokens' | 'chains' | 'brands',
): { dispatcher: string; shards: Map<string, string> } {
  const lazy = assets.filter((a) => !a.bundle)

  // file key -> ids in that shard file.
  const fileGroups = new Map<string, string[]>()
  // first-char key -> file key it dispatches to.
  const keyToFile = new Map<string, string>()

  if (lazy.length <= SHARD_FANOUT_THRESHOLD) {
    const ids = lazy.map((a) => a.id)
    if (ids.length > 0) {
      fileGroups.set(SINGLE_SHARD_KEY, ids)
      for (const a of lazy) {
        keyToFile.set(shardKey(a.id), SINGLE_SHARD_KEY)
      }
    }
  } else {
    for (const a of lazy) {
      const key = shardKey(a.id)
      // One file per first char; the file key IS the first char.
      keyToFile.set(key, key)
      const group = fileGroups.get(key) ?? []
      group.push(a.id)
      fileGroups.set(key, group)
    }
  }

  const dispatcher = generateLazyDispatcher(dirName, keyToFile)

  const shards = new Map<string, string>()
  for (const [fileKey, ids] of fileGroups) {
    shards.set(fileKey, generateLazyShardFile(dirName, ids))
  }

  return { dispatcher, shards }
}

// The per-type dispatcher: SHARD_IMPORTS maps a first-char key to a thunk that
// statically imports the shard file holding that key's ids. Lazy-icons.ts
// indexes this by `id[0]`.
function generateLazyDispatcher(
  dirName: 'tokens' | 'chains' | 'brands',
  keyToFile: Map<string, string>,
): string {
  const lines: string[] = [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    "import type { ComponentType } from 'react'",
    "import type { IconProps } from '../../icon-props'",
    '',
    'type Loader = () => Promise<{ default: ComponentType<IconProps> }>',
    'type Shard = {',
    '  ICON_IMPORTS: Record<string, { full: Loader; mono: Loader }>',
    '}',
    '',
    'export const SHARD_IMPORTS: Record<string, () => Promise<Shard>> = {',
  ]
  // Sort keys for stable output.
  for (const key of [...keyToFile.keys()].sort()) {
    const file = keyToFile.get(key)!
    lines.push(
      `  ${JSON.stringify(key)}: () => import('./${dirName}/${file}'),`,
    )
  }
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

// One shard file: the id -> per-variant import-thunk map for the ids that fall
// into it. Each id maps to { full, mono } thunks so a mono-only render only
// ever downloads the mono variant chunk.
function generateLazyShardFile(
  dirName: 'tokens' | 'chains' | 'brands',
  ids: string[],
): string {
  const lines: string[] = [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    "import type { ComponentType } from 'react'",
    "import type { IconProps } from '../../../icon-props'",
    '',
    'type Loader = () => Promise<{ default: ComponentType<IconProps> }>',
    '',
    'export const ICON_IMPORTS: Record<',
    '  string,',
    '  { full: Loader; mono: Loader }',
    '> = {',
  ]
  for (const id of ids) {
    lines.push(
      `  ${JSON.stringify(id)}: { full: () => import('../../${dirName}/${id}.full'), mono: () => import('../../${dirName}/${id}.mono') },`,
    )
  }
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function generateEagerMap(
  tokens: TokenAsset[],
  chains: ChainAsset[],
  brands: BrandAsset[],
): string {
  const eagerTokens = tokens.filter((t) => t.bundle)
  const eagerChains = chains.filter((c) => c.bundle)
  const eagerBrands = brands.filter((b) => b.bundle)

  const lines: string[] = [
    '// Auto-generated by scripts/generate.ts - DO NOT EDIT',
    "import type { ComponentType } from 'react'",
    "import type { IconProps } from '../icon-props'",
    '',
  ]

  // Alias every local binding by type. createComponentName is unique only
  // WITHIN a type (assertUniqueComponentNames), but this one module imports
  // all three types — a cross-type duplicate id (token `eth` + chain `eth`,
  // both bundled) or two ids that converge on one component name across types
  // would otherwise emit the same import identifier twice and fail to compile.
  // `Token`/`Chain`/`Brand` + the per-type-unique name is globally unique.
  const local = (type: 'Token' | 'Chain' | 'Brand', id: string) =>
    `${type}_${createComponentName(id)}`

  // Static imports
  for (const t of eagerTokens) {
    lines.push(
      `import { ${createComponentName(t.id)} as ${local('Token', t.id)} } from './tokens/${t.id}'`,
    )
  }
  for (const c of eagerChains) {
    lines.push(
      `import { ${createComponentName(c.id)} as ${local('Chain', c.id)} } from './chains/${c.id}'`,
    )
  }
  for (const b of eagerBrands) {
    lines.push(
      `import { ${createComponentName(b.id)} as ${local('Brand', b.id)} } from './brands/${b.id}'`,
    )
  }

  lines.push('')
  lines.push(
    'export const EAGER_ICONS: Record<string, ComponentType<IconProps>> = {',
  )

  for (const t of eagerTokens) {
    lines.push(`  ${JSON.stringify(`token:${t.id}`)}: ${local('Token', t.id)},`)
  }
  for (const c of eagerChains) {
    lines.push(`  ${JSON.stringify(`chain:${c.id}`)}: ${local('Chain', c.id)},`)
  }
  for (const b of eagerBrands) {
    lines.push(`  ${JSON.stringify(`brand:${b.id}`)}: ${local('Brand', b.id)},`)
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

// --- Output helpers ---

const aliasWarnings: string[] = []
const sameTypeCollisions: AliasCollision[] = []

// --- Manifest-diff write phase ---
//
// Replaces the old "wipe the dir up front" cleanup. Wiping defeated the
// skip-identical optimisation (every file looked new). Instead: collect the
// set of generated files currently on disk under the gen roots, write only
// the ones whose content changed, and delete the ones we no longer produce.
function listGeneratedFiles(root: string): string[] {
  if (!existsSync(root)) return []
  const out: string[] = []
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const p = resolve(dir, entry.name)
      if (entry.isDirectory()) walk(p)
      else out.push(p)
    }
  }
  walk(root)
  return out
}

function writeOutputs(): { written: number; skipped: number; removed: number } {
  // Ensure parent dirs exist for every output.
  const dirs = new Set<string>()
  for (const path of outputs.keys()) {
    dirs.add(resolve(path, '..'))
  }
  for (const dir of dirs) mkdirSync(dir, { recursive: true })

  let written = 0
  let skipped = 0
  for (const [path, content] of outputs) {
    // Skip writing files whose on-disk content is already identical, to
    // avoid mtime churn that retriggers watchers/build caches.
    if (existsSync(path) && statSync(path).isFile()) {
      try {
        if (readFileSync(path, 'utf-8') === content) {
          skipped++
          continue
        }
      } catch {
        // fall through to write
      }
    }
    writeFileSync(path, content)
    written++
  }

  // Remove stale generated files no longer produced.
  let removed = 0
  for (const root of [CORE_GEN, REACT_GEN]) {
    for (const existing of listGeneratedFiles(root)) {
      if (!outputs.has(existing)) {
        rmSync(existing, { force: true })
        removed++
      }
    }
  }

  // Prune now-empty directories left behind by removals.
  for (const root of [CORE_GEN, REACT_GEN]) {
    pruneEmptyDirs(root)
  }

  return { written, skipped, removed }
}

function pruneEmptyDirs(dir: string) {
  if (!existsSync(dir)) return
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) pruneEmptyDirs(resolve(dir, entry.name))
  }
  if (readdirSync(dir).length === 0) {
    rmSync(dir, { recursive: true, force: true })
  }
}

// --- Main ---

const t0 = performance.now()

console.log()
console.log(bold('  @bgd-labs/icons — generate'))
console.log()

const catalogue = loadCatalogue()
const { tokens, chains, brands, frames } = catalogue

// Distinct ids can normalise to the same component name ("1inch" and
// "oneinch" both become OneInchIcon) — that would emit duplicate exports in
// a barrel, surfacing as an opaque tsc error. Fail with the colliding pair.
function assertUniqueComponentNames(
  assets: readonly { id: string }[],
  kind: string,
  suffix = 'Icon',
) {
  const seen = new Map<string, string>()
  for (const a of assets) {
    const name = createComponentName(a.id, suffix)
    const prior = seen.get(name)
    if (prior !== undefined) {
      throw new Error(
        `Component name collision in ${kind}: "${prior}" and "${a.id}" both generate ${name}`,
      )
    }
    seen.set(name, a.id)
  }
}

assertUniqueComponentNames(tokens, 'tokens')
assertUniqueComponentNames(chains, 'chains')
assertUniqueComponentNames(brands, 'brands')
assertUniqueComponentNames(frames, 'frames', 'Frame')

const totalAssets =
  tokens.length + chains.length + brands.length + frames.length
console.log(
  `  ${dim(padLabel('Assets', 18))} ${tokens.length} tokens, ${chains.length} chains, ${brands.length} brands, ${frames.length} frames ${dim(`(${totalAssets} total)`)}`,
)
console.log()

// --- Core Package (built into memory) ---

emit(resolve(CORE_GEN, 'meta.ts'), generateCoreMeta(tokens, chains, brands))
emit(resolve(CORE_GEN, 'ids.ts'), generateCoreIds(tokens, chains, brands))
emit(resolve(CORE_GEN, 'aliases.ts'), generateCoreAliases(catalogue))
emit(
  resolve(CORE_GEN, 'svg/tokens.ts'),
  generateCoreSvgExports(tokens, 'token'),
)
emit(
  resolve(CORE_GEN, 'svg/chains.ts'),
  generateCoreSvgExports(chains, 'chain'),
)
emit(
  resolve(CORE_GEN, 'svg/brands.ts'),
  generateCoreSvgExports(brands, 'brand'),
)

// --- React Package (built into memory) ---

const tokensDir = resolve(REACT_GEN, 'tokens')
const chainsDir = resolve(REACT_GEN, 'chains')
const brandsDir = resolve(REACT_GEN, 'brands')
const framesDir = resolve(REACT_GEN, 'frames')

for (const t of tokens) emitComponentTrio(tokensDir, t.id, assetSpec(t))
emit(resolve(tokensDir, 'index.ts'), generateReactBarrelIndex(tokens))

for (const c of chains) emitComponentTrio(chainsDir, c.id, assetSpec(c))
emit(resolve(chainsDir, 'index.ts'), generateReactBarrelIndex(chains))

for (const b of brands) emitComponentTrio(brandsDir, b.id, assetSpec(b))
emit(resolve(brandsDir, 'index.ts'), generateReactBarrelIndex(brands))

// Frames are statically imported (never lazy) but share the same per-variant
// + combined template. No barrel: consumers import frames via src/frames.ts,
// which pulls the per-frame modules directly.
for (const f of frames) emitComponentTrio(framesDir, f.id, frameSpec(f))

// Lazy dispatchers (per-type, first-char keyed) + sub-shard files + eager map
function emitLazyType(
  assets: (TokenAsset | ChainAsset | BrandAsset)[],
  dirName: 'tokens' | 'chains' | 'brands',
) {
  const { dispatcher, shards } = generateLazyType(assets, dirName)
  emit(resolve(REACT_GEN, `lazy/${dirName}.ts`), dispatcher)
  for (const [fileKey, content] of shards) {
    emit(resolve(REACT_GEN, `lazy/${dirName}/${fileKey}.ts`), content)
  }
}
emitLazyType(tokens, 'tokens')
emitLazyType(chains, 'chains')
emitLazyType(brands, 'brands')
emit(
  resolve(REACT_GEN, 'eager-map.ts'),
  generateEagerMap(tokens, chains, brands),
)

// --- Gate: fatal collisions abort BEFORE any write ---

if (aliasWarnings.length > 0) {
  console.log()
  console.log(`  ${yellow(`Alias collisions (${aliasWarnings.length}):`)}`)
  for (const w of aliasWarnings) {
    console.log(`  ${yellow('~')} ${w}`)
  }
}

// Same-type collisions are authoring errors: the losing alias silently never
// resolves and the winner is picked by catalogue order. validate.ts reports
// them with context; this is the backstop for direct `generate` runs. Abort
// before writing anything so a failed generate never leaves poisoned output.
if (sameTypeCollisions.length > 0) {
  console.log()
  console.log(
    `  same-type alias collisions (${sameTypeCollisions.length}) — generation aborted (nothing written):`,
  )
  for (const { key, kept, dropped } of sameTypeCollisions) {
    console.log(
      `  x "${key}": ${dropped.type}:${dropped.id} collides with ${kept.type}:${kept.id}`,
    )
  }
  console.log()
  process.exit(1)
}

// --- Write phase (only reached when known-good) ---

const { written, skipped, removed } = writeOutputs()

const eagerCount = [...tokens, ...chains, ...brands].filter(
  (a) => a.bundle,
).length
const lazyCount = [...tokens, ...chains, ...brands].filter(
  (a) => !a.bundle,
).length
const componentCount =
  tokens.length + chains.length + brands.length + frames.length

console.log(
  `  ${cyan(padLabel('@bgd-labs/icons', 18))} meta.ts  ids.ts  aliases.ts  svg/{tokens,chains,brands}.ts`,
)
console.log(
  `  ${cyan(padLabel('@bgd-labs/icons-react', 18))} ${componentCount} components ${dim(`(${eagerCount} eager, ${lazyCount} lazy)`)}`,
)
console.log(
  `  ${dim(padLabel('Files', 18))} ${written} written, ${skipped} unchanged, ${removed} stale removed`,
)

// --- Done ---

const elapsed = Math.round(performance.now() - t0)
console.log()
console.log(`  ${green('done')} in ${elapsed}ms`)
console.log()
